### ISSUE TITLE
copyright statement

### ISSUE THREAD

**Issue by waldenn** [Bewelge/MIDIano#12]
Hi there. Could you please add a license / copyright statement to the repo? Thanks!

**Comment by Bewelge** [comment]
Hey there, 
sorry for the late reply. As stated in the readme, I'm not granting any license on this project and retain all rights. 

I've simply left the code public because I want to allow people to learn from it. If you are interested in using specific parts of the project you can contact me at "contact (at) midiano (dot) com". I might be open to that if you're not planning on creating a too similar product ;-)
