### ISSUE TITLE
[suggestion] Make the website available offline with a desktop app

### ISSUE THREAD

**Issue by leo-t-88** [Bewelge/MIDIano#59]
I don't know if this is really feasible and a good suggestion.
But I think it would be great if this web application could be used locally offline, maybe it could be possible with electron for example.

**Comment by Bewelge** [comment]
Hey, this should already work since most files are cached. I think there will be only one soundfont available and it may not load all the default songs but apart from that it should all work offline. In case your browser doesn't allow that you can install it as a Progressive Web app (just search for "install PWA" for the browser of your choice) which should always trigger the caching of files and make it work offline. 

Let me know if that works :)

**Comment by leo-t-88** [comment]
I tried it and it works fine offline, thanks!
