### ISSUE TITLE
Synchro metronome

### ISSUE THREAD

**Issue by Gui-Tahar** [Bewelge/MIDIano#8]
Hi,
There is a loss of metronome sync when changing the speed.

**Comment by Bewelge** [comment]
Hey there, 

I'll have a look at it tonight :)

**Comment by Bewelge** [comment]
Just pushed a fix. 
The metronome sound works like the note sounds in that it is scheduled a couple of miliseconds before it happens. Turns out that these couple of miliseconds did not account for the current speed. So the intervals were still correct but the synch was not. Good catch! I barely noticed. Let me know if it works now, then I will close.

**Comment by Gui-Tahar** [comment]
More than perfect ;-)
