### ISSUE TITLE
Suggestion: SheetMusic

### ISSUE THREAD

**Issue by akfldk1028** [Bewelge/MIDIano#9]
Hello, I'm one of those people who study midi related sheet music. I looked at the project code to see how the midi of the current project was transformed into sheet music, but I found out that there is currently no sheet music related code. I'd like to ask if it's possible to update the project with sheet music.

**Comment by Bewelge** [comment]
Hey there,
Thanks for showing interest in the Midiano and how it's built. Unfortunately I no longer publicly publish the source code and the Sheet Generation is actually in such a messy state that I'm not sure it would help you anyways. 

You should check out Musescore and Lilypond. They are both mature open-source programs that offer MIDI to Sheet conversion. 

Alternatively, since I don't minify the js files,  you can simply check the source on Midiano.com by opening the developers console of your browser. The files for the sheet generation & rendering are under /js/sheet/. 

If you have any more questions about how the code works you can write me an email to contact(at)midiano.com. Best of luck :-)

**Comment by 1ncursio** [comment]
Hello Bewelge.

I am currently working on a midi piano project as a graduation project. Responsive sheet music is also required for that.

If you don't mind, may I refer to MIdiano for my project? I will reveal the source.

**Comment by Bewelge** [comment]
Hey there,

Sorry for the late reply. Do you mean by "refering" to use the source-code in your project? I have not and am not planning to release the code under any open license. In general I wouldn't be opposed to allow using parts of the code for a purely educational project but that would mean that you would not be allowed to publicly publish your project afterwards. If I remember projects from my university years I'm guessing that would rule out using my code. If you want to discuss it further however, please reach out by mail at contact(at)midiano.com.

All the best and good luck with your project!
